# Generated by Django 3.0.8 on 2020-08-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200805_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(default='Just for fun!', max_length=50),
            preserve_default=False,
        ),
    ]
